### ISSUE TITLE
Basic paste API

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#1]
🏃= in progress
🔑= requires api key (all requests on a private paste require api key, otherwise 404)

- [x] `/api/pastes`
  - [x] `GET` - n most recent pastes
  - [x] `POST`
  - [x] `/<id>`
    - [x] `GET`
    - [x] `PATCH` 🔑
    - [x] `DELETE` 🔑 (also uses deletion keys)
    - [x] `/files`
      - [x] `GET`
      - [x] `POST` 🔑
      - [x] `PATCH` 🔑
      - [x] `/<id>`
        - [x] `GET`
        - [x] `PATCH` 🔑
        - [x] `DELETE` 🔑
        - [x] `/raw`
          - [x] `GET`

**Comment by lol768** [comment]
- [ ] Lrn2document URLs

**Comment by jkcclemens** [comment]
Basic API finished with https://github.com/jkcclemens/paste/commit/04c318ab5d4c622d49ae41ec7a13495290746ca0. Any bugs or new features will be new issues.
