### ISSUE TITLE
Command line client

### ISSUE THREAD

**Issue by svenstaro** [jkcclemens/paste#101]
**Is your feature request related to a problem? Please describe.**
I'd like a proper command line client to paste. Perhaps it could default to paste.gg.

**Describe the solution you'd like**
A pastebin command line client supporting the specific API of paste.

**Describe alternatives you've considered**
Could do it using curl but that kind of sucks from a UX perspective.

**Additional context**
Other pastebins have such CLI such as fpaste.

**Comment by AKPWebDesign** [comment]
Have you tried https://github.com/jkcclemens/bins ?

**Comment by svenstaro** [comment]
Well, that's that, then.

**Comment by svenstaro** [comment]
Perhaps there should be some visibility for that on paste.gg or on this README.
