### ISSUE TITLE
Preload light theme

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#102]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't see a `Link: </static/css/style.css?v=916db97bd57414436f8688d73b37a2d7a7ea62a7>; rel=preload; as=style` response header.

**Describe the solution you'd like**
I'd like a `Link: </static/css/style.css?v=916db97bd57414436f8688d73b37a2d7a7ea62a7>; rel=preload; as=style` response header to be sent. A good HTTP/2 server should do push.

**Describe alternatives you've considered**
Not sending `Link` header, as we do now.

**Comment by jkcclemens** [comment]
Done in 86f8db88d7920df2744a1abb70432dfd256c02fc.
