### ISSUE TITLE
The login menu is not keyboard accessible

### ISSUE THREAD

**Issue by notriddle** [jkcclemens/paste#117]
**Describe the bug**
It is impossible to reach the Register or Swap Theme buttons using only the keyboard.

**To Reproduce**
1. Open paste.gg
2. Press tab until the Login button is highlighted.
3. Pressing enter does not open the menu. It takes you to the login page.
4. The "Register" and "Swap theme" buttons are not accessible anywhere other than that menu.

**Expected behavior**
Pressing "Enter" when the menu is focused should open the menu. Alternatively, the menu should pop open when you tab into it, and stay open until you tab through its items.

**Screenshots**

![image](https://user-images.githubusercontent.com/1593513/55597973-30ff4700-5705-11e9-968d-f505c84fb511.png)

**Server and resources version (found in footer)**

 - Server: d4bf1ab
 - Resources: d4bf1ab

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox
 - Version: 66.0.2

**Comment by lol768** [comment]
I suggest we just make it clickable, not hoerable. Keyboard nav works fine with the clickable ones in the Bulma docs

**Comment by lol768** [comment]
https://github.com/jgthms/bulma/pull/2321

**Comment by jkcclemens** [comment]
It looks as if that PR was merged. Bulma just needs to be updated.

**Comment by lol768** [comment]
Let's update Bulma

**Comment by jkcclemens** [comment]
This is partially fixed in prod, but the swap theme item is not keyboard accessible for me.

**Comment by jkcclemens** [comment]
Done in 8e1a159b35de8ef579b29c9359074423d9fb5804!
