### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by Soaku** [jkcclemens/paste#118]
I'm hosting a small app on GitHub Pages, or more precisely a little interpreter, which gives an option to get a permalink to the currently developed script and some data such an evaluation options and unit tests – so they can be later easily shared to other users. The files shouldn't be larger than 3 KB, but the most will be much smaller, less than 0.5 KB. 

Paste.gg seems like a perfect service – because it enables easy code sharing.  The problem is, GH Pages doesn't provide any server side scripts, so all requests must be done with client-side JS. Because the paste.gg API doesn't provide a [CORS header](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), response data cannot be read.

My suggestion is to add the `Access-Control-Allow-Origin: *` to API responses. Since user login data is sent via the API as a parameter, the request cannot be posted to the server in the user's name without permission anyway.

Alternative: Of course, I could send the request through my server, but I feel like it could and should be simpler.

Thanks!

**Comment by lol768** [comment]
As long as we never send `Access-Control-Allow-Credentials` (specifying a literal `*` for `Access-Control-Allow-Origin` will disallow creds use anyway), I think this is fine on public API endpoints and greatly preferable to e.g. JSONP.
