### ISSUE TITLE
Showing {1} on blank line

### ISSUE THREAD

**Issue by jtrakk** [jkcclemens/paste#119]
In line 3 of [this paste](https://paste.gg/p/anonymous/d315568503f84efc9dbc46da126077b9) I see `{1}` but those characters don't appear in the raw, and they are not in the original code that I copied.

**Comment by jkcclemens** [comment]
This issue has come up before. I'll have to figure out what was happening there.

**Comment by jkcclemens** [comment]
This will be fixed when server-side highlighting is implemented.
