### ISSUE TITLE
Default form submit on enter creates an anonymous paste even when logged in

### ISSUE THREAD

**Issue by bendem** [jkcclemens/paste#120]
**Describe the bug**

See title

**To Reproduce**

* Login
* Create paste
* focus header field
* press enter

**Expected behavior**

Paste tied to your account

**Screenshots**
 
meh

**Server and resources version (found in footer)**
This is too hard to select, current staging

**Desktop (please complete the following information):**
irrelevant

**Smartphone (please complete the following information):**
irrelevant

**Additional context**
meh

**Comment by WofWca** [comment]
I'll work on this if you don't mind.

**Comment by jkcclemens** [comment]
Feel free!

**Comment by jkcclemens** [comment]
@WofWca If you need a little guidance, the HTML 5 [standard][standard] has information on how implicit submission (pressing Enter here) works. There's a way to make the authenticated submission the default without changing how the page looks!

[standard]: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission
