### ISSUE TITLE
The text in the footer is hard to select

### ISSUE THREAD

**Issue by bendem** [jkcclemens/paste#121]
**Describe the bug**
Bug report asks for information in the footer, but it's a pain to copy/paste

**To Reproduce**

* Try to copy paste the resource and server text in the footer
* pester
* give up

**Expected behavior**

* click on the left of the text
* hold and move to right of the text
* copy

**Screenshots**
meh

**Server and resources version (found in footer)**
...

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox nightly
 - Version 70

**Smartphone (please complete the following information):**
irrelevant

**Additional context**

**Comment by lol768** [comment]
<kbd>Alt</kbd>, @bendem

**Comment by jkcclemens** [comment]
Changing the `padding` to `margin` on the links in the footer would fix this.
