### ISSUE TITLE
Frontend pre-requisites

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#17]
- [x] Some way to serve static files
  - https://github.com/compass-rs/sass-rs as part of build process?
- [x] Plan of frontend routes
  - `GET /`, `POST /`, `GET /<paste_id>`, `GET /<paste_id>/edit`, `POST /<paste_id>/edit`, `GET /<paste_id>/files/<file_id>|<file_name>`?
- [x] Example templates

**Comment by kashike** [comment]
`<username>` = `anonymous` for non-authenticated

- `GET /<username>`
  - list public pastes, or all if you're the person
- `GET /<username>/<paste id>`
- `GET /<username>/<paste id>/edit`
- `POST /<username>/<paste id>/edit`
... etc

**Comment by jkcclemens** [comment]
- [x] GET `/`
  - Primary paste creation interface.
- [x] POST `/pastes`
  - Route to create a paste via web.

- [ ] GET `/about`
  - maybe?

- [ ] GET `/username`
  - View public pastes (all if authed)
  - Takes precedence over GET `/<id>`
- [x] GET `/<id>`
  - Redirect to `/<username>/<id>`
- [x] GET `/<username>/<id>`
  - Display paste, its info, and its files.
- [ ] GET `/<username>/<id>/edit`
  - Edit paste information and files.
- [ ] POST `/<username>/<id>/edit`
  - Save changes.
- [ ] POST `/<username>/<id>/delete`
  - Delete paste.
- [ ] GET `/<username>/<id>/files/<id>/edit`
  - Edit one file.
- [ ] POST `/<username>/<id>/files/<id>/edit`
  - Save changes.
- [ ] POST `/<username>/<id>/files/<id>/delete`
  - Delete file.

- [x] GET `/account`
  - Display and allow account information edits.
- [x] POST `/account`
  - Make account information edits.
- [x] GET `/account/keys`
  - Display API keys.
- [x] POST `/account/keys`
  - Create a new API key.
- [x] POST `/account/keys/<key>/delete`
  - Delete an API key.
- [x] POST `/account`
- [x] GET `/account/delete`
