### ISSUE TITLE
Deletion 404

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#183]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I get a 404 with flash message after I admin-delete a paste

**Describe the solution you'd like**
Redirect to homepage with flash message (or somewhere else!)

**Describe alternatives you've considered**
Not redirecting to the homepage with a flash message (or anywhere else)

**Additional context**
No

**Comment by jkcclemens** [comment]
>:(

**Comment by Zarthus** [comment]
Frustrating lol768 sounds like a feature to me.

**Comment by lol768** [comment]
I'm frustrated by every issue I make because the issue template requires me to be frustrated

**Comment by jkcclemens** [comment]
So, the admin deletion route is the same route for the paste list and for individual pastes. It currently is set up to take you back to your last page. This works for the admin paste list, but it results in the 404 for deleting a paste from its page.

Is there a reasonable place to bring the user for both? Taking the user always back to the admin paste list could work, or it could branch depending on where the user came from. Could add a flag if coming from a paste itself and redirect back to index.
