### ISSUE TITLE
Use libsodium to encrypt private files

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#20]
Use `pwhash` key derivation to encrypt private files? This would require rekeying files on password change.

Necessary?

**Comment by lol768** [comment]
Regarding doing this client-side..

https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/

**Comment by jkcclemens** [comment]
So I suppose we'll have to prompt for password when viewing a private paste in order to decrypt?

**Comment by lol768** [comment]
I can think of a few points here:

* Prompt the user for a password which is then sent server-side.
  * Drawback: server sees password, but more convenient.
* On the password prompt page, also include a _download_ button and/or command the user can copy and issue to download and decrypt the file locally using tools on their own machine - if they desire.

**Comment by jkcclemens** [comment]
>Prompt the user for a password which is then sent server-side.

Another pertinent question is how do we handle them reloading the page or editing and so on without them re-entering the password?

Store the password in memory? Decrypt the file on the server for a period of time?

**Comment by lol768** [comment]
>Another pertinent question is how do we handle them reloading the page or editing and so on without them re-entering the password?

>Store the password in memory? Decrypt the file on the server for a period of time?

This is a good question, and I think you've already suggested the approaches I'd have mentioned. I'm not sure I like the idea of storing the password in memory... but what's the alternative? It could go in `window.sessionStorage` and then be sent to the server for each operation (fetch, refresh, edit) and then the UX would be a bit better. The downside of course is that this is then accessible if there's an XSS.

You could store it in a `HttpOnly`, `SameSite=strict`, `Path`-constrained session cookie (e.g. could be only available to stuff under `/private/` to limit attack surface<sup>1</sup>). This wouldn't be accessible from anything client-side and would only be accessible to the server in the context of the relevant requests. You'd want some way to expire the cookie - maybe have it only valid for ten minutes at a time.

----------

1. What's the risk? It's unlikely, but if there was a vuln. in something under e.g. an `/uploads/` directory or elsewhere on the site (maybe an SSRF that forwarded the client request headers) the cookie would not be sent.

**Comment by jkcclemens** [comment]
Alright, I've started work on this. I have some notes and questions, but I'd like to detail the process for encryption and decryption and get @lol768's opinion.

### Encrypting

1. The plaintext password is provided by the user at the time of paste creation.
2. The password is hashed in the same manner as account passwords, and it is stored as part of the paste in the database.
3. The password is used to [create a secret key](https://sodiumoxide.github.io/sodiumoxide/sodiumoxide/crypto/pwhash/scryptsalsa208sha256/fn.derive_key.html) using the salt that was used to hash the password in step 2.
4. A nonce is generated.
5. The nonce is used with the derived key and plaintext file data to create a [secret box](https://sodiumoxide.github.io/sodiumoxide/sodiumoxide/crypto/secretbox/index.html).
6. The nonce is written to the disk, followed by the encrypted data.
7. Repeat steps 4-6 for each file.

### Decrypting

1. The plaintext password is provided by the user at the time of paste retrieval.
    - If using the web UI, the user is prompted to provide the password if a password is set on the paste. Upon submitting the password, it is checked, and if it is valid, it is stored in an `HttpOnly`, `Secure`, `Path`-constrained (constrained to that paste specifically), encrypted, authenticated, cookie that expires in 15 minutes. The expiration time is updated every time a request to the paste is made.
    - If using the web UI with a cookie set, the cookie is read and used without user intervention. If the password stored in the cookie is incorrect, the user is prompted to provide the correct password.
    - If using the API, requesting an encrypted paste without specifying a password is an error, and the client will have to try again.
2. The password is checked against the hashed password.
3. If correct, the password is used to derive a secret key, using the salt stored in the database (step 2 of encryption).
4. The encrypted file is read, and the nonce and data are separated.
5. The secret box is opened, using the key, nonce, and encrypted data.
6. Repeat steps 4-5 for each file.
7. Serve the decrypted data to the user.

No plaintext data is ever saved or stored. It only exists in memory for as long as necessary.

### Notes/questions

- Currently, the paste title and description are plaintext only. Should they also be encrypted?
- Revisions are more difficult with encrypted data. Git never sees the plaintext, so each change would require a diff to be generated and encrypted, then stored on the disk. I vote for disabling revisions on encrypted pastes.
- Each edit to a paste requires the password, which will require some internal refactoring.

**Comment by jkcclemens** [comment]
After some time away from actively working on this and reflection, I think that this is not a necessary feature.

- Anyone who is concerned about this can use GPG (symmetric and asymmetric) and upload ASCII armoured output or any other encryption method.
  - paste supports the ability to programmatically upload pre-encrypted data and download it to decrypt client-side. The API for upload and download or using raw files for download to decrypt works just fine.
- Personally, I don't like handling encryption and decryption on the server side, since a malicious server can read the data and it introduces an extra party into the exchange of encrypted data.
- The only benefit of encrypted pastes that is lost by having users encrypt before upload is ease of access. Considering this is a tool made primarily for programmers, I don't envision this being a real issue. However, encrypting before upload (potentially) adds several security benefits which makes up for the loss of ease of access.

If anyone has objections to this not being implemented, let me know. Otherwise, I'll close this and delete the `encryption` branch eventually.

**Comment by lol768** [comment]
Not mentioned in this issue is the extensive discussion on IRC around this. Following said discussion, I support not implementing this. Perhaps too many technical details had been discussed instead of effort answering "What problem does this solve, what is the threat model?".

However, you may wish to create a documentation issue explaining how folks can use e.g. keybase or gpg and pipe the output to get a paste they can share.

**Comment by jkcclemens** [comment]
>Perhaps too many technical details had been discussed instead of effort answering "What problem does this solve, what is the threat model?".

In fact, it was mostly you bringing this up that made me realise that this is mostly a useless feature.

>However, you may wish to create a documentation issue explaining how folks can use e.g. keybase or gpg and pipe the output to get a paste they can share.

My thoughts exactly!
