### ISSUE TITLE
cannot send email

### ISSUE THREAD

**Issue by ybaumy** [jkcclemens/paste#231]
> sidekiq_1   | could not send email: handshake error

Cannot send email via TLS nor SSL. Is there a way to configure more options or only the target port?

**Comment by jkcclemens** [comment]
Are you saying that you are trying to send email via TLS or that you need to be able to send email without TLS?

If you want email without TLS, I'm not sure if I want to enable insecure email transport. Could you explain why you want this?

**Comment by lol768** [comment]
When we say TLS, do we mean an _actual_ TLS connection (SYN-ACK-SYNACK + _immediate_ ClientHello from the get go) or the joke that is also known elsewhere as STARTTLS?

**Comment by ybaumy** [comment]
I guess the problem is that it is a self signed cert on a private box. If I decide to use this as my pastebin and put it on a cloud instance, I will have a official cert and try to send mails again.

**Comment by lol768** [comment]
If it's a private box, you could provision your own CA and then sign the entity's cert with that. Your root can go in your own trust store.

**Comment by ybaumy** [comment]
too much overhead for just trying tbh.

**Comment by ybaumy** [comment]
Yes this pretty much the certificate. I verified it with using another server with the SMTP relay I have to use. And there it works
