### ISSUE TITLE
Use precedence and redirects for username/route conflicts

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#24]
How do we handle usernames like `anonymous` or `account` when they conflict with routes of the same name?

Especially with GET `/<username>` planned, this will become an issue.

- Blacklist certain usernames
- Use Reddit-style `/u/<username>`
  - Does this then become GET `/u/<username>/<id>` for pastes?

**Comment by lol768** [comment]
I support the idea of having an alias of `/<username>` ⇔ username is NOT reserved (anonymous, account)

**Comment by jkcclemens** [comment]
So do something like have `/<user>/<username>` for explicit users, then `/<username>` when username isn't already a route is a redirect to `/<user>/<username>`?

This will make a paste URL become `/user/myname/90d4f086d3354cd08b179c9dc140eb1d`, but `/myname/90d4f086d3354cd08b179c9dc140eb1d` and `/90d4f086d3354cd08b179c9dc140eb1d` would both redirect there.
