### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#27]
### Content Security Policy

* Suggest implemented using a _Fairing_ for CSP headers
* Should be strict, I suggest:

```
Content-Security-Policy:
  default-src: 'self'
  object-src 'none';
  script-src 'self' https://use.fontawesome.com/;
  require-sri-for script style;
  frame-ancestors 'none';
  base-uri 'none';
  block-all-mixed-content;
  report-uri https://paste.gg/csp/report
```

- [x] Implemented
- [ ] Implemented with reporting

-----

Previously, on issue #27:

### ~Referrer Policy~

```
Referrer-Policy: no-referrer
```

- [x] Implemented

### ~X-XSS-Protection~

```
X-XSS-Protection: 1; mode=block
```

- [x] Implemented

### ~X-Frame-Options~

~Duplicates `frame-ancestors`, for older browsers/those that don't support the CSP directive:~

```
X-Frame-Options: DENY
```

- [x] Implemented

### ~X-Content-Type-Options~

~Disables MIME sniffing.~

```
X-Content-Type-Options: nosniff
```

- [x] Implemented

### ~Strict-Transport-Security~

~Suggested value:~

```
Strict-Transport-security: max-age=31536000; includeSubDomains
```

- [x] Implemented

### ~Expect-CT~

~Suggested value:~

```
max-age=604800
```

- [x] Implemented

**Comment by jkcclemens** [comment]
STS is done via `nginx` currently, and Expect-CT I think Cloudflare adds.

**Comment by lol768** [comment]
Do we want them in the Rust fairing too?

**Comment by jkcclemens** [comment]
STS definitely no. We don't handle TLS in Rocket ([yet](https://rocket.rs/guide/configuration/#configuring-tls)).

**Comment by jkcclemens** [comment]
See the [`csp`](https://github.com/jkcclemens/paste/tree/csp) branch.

Currently, reCAPTCHA (can't SRI because not versioned and contents change – nonce doesn't bypass `require-sri-for`) and Ace are making this very difficult.

**Comment by lol768** [comment]
> Currently, reCAPTCHA (can't SRI because not versioned and contents change

Google should know better than this. Can you host your own copy of it or look at alternative CAPTCHA solutions?

>Ace are making this very difficult

Why? Same issue?

**Comment by jkcclemens** [comment]
> Can you host your own copy of it or look at alternative CAPTCHA solutions?

I can try, but I feel like if they change their version, ours will break.

> Why? Same issue?

https://github.com/ajaxorg/ace/issues/3260

Loads inline styles. The `innerHTML` bit they're talking about got a PR that was merged. Ace is all local, but it loads JS and CSS on the fly for syntax highlighting schemes and themes. [CodeMirror](http://codemirror.net/) is mentioned as an alternative, but I don't know if it can do what we need it to, and I don't know if it has CSP support.

**Comment by kashike** [comment]
It's worth noting that the [javascript](https://www.google.com/recaptcha/api.js) has the following comment: `/* PLEASE DO NOT COPY AND PASTE THIS CODE. */`

**Comment by kashike** [comment]
The problem is that the link found in https://www.google.com/recaptcha/api.js can change at anytime, and you would end up serving an old, and potentially broken, version.

**Comment by lol768** [comment]
Depends if they value BC or not, but yeah it's a risk.

**Comment by jkcclemens** [comment]
I think that no matter what we do, we're going to be forced to loosen our CSP restrictions. I don't think there is any code editor out there (aside from maybe [CodeFlask](https://kazzkiq.github.io/CodeFlask.js/), which I do not think is full-featured enough, and I haven't even fully looked into CSP with it) that will work with us denying inline styles.

**Comment by lol768** [comment]
It's a shame, but completely understandable. A lot of the clients I work with end up in the same situation. They have tooling/libraries they want to use which require unsafe CSP directives. It sucks even more when the maintainers are too arrogant to fix their shit, too.

CodeFlask looks like it uses classes for the various tokens. I see no reason why all code editors shouldn't be able to do this.

Out of curiousity, what functionality do you think CodeFlask is missing?

**Comment by jkcclemens** [comment]
After looking more at CodeFlask, the only thing it doesn't have is tab continuation on new line. It'd require us to switch to Prism.js for highlighting (CodeFlask requires it and no reason to use two different highlighters), but I was already looking for that.

I would really prefer it have the ability to continue indents, though.

**Comment by lol768** [comment]
> I would really prefer it have the ability to continue indents, though.

Yeah, that's one of the first things I noticed when playing with it..

**Comment by lol768** [comment]
https://github.com/lol768/CodeFlask should unblock this, regardless of the Prism/highlightjs debate

**Comment by jkcclemens** [comment]
This is now on staging. If people with staging access could poke around a bit to verify that it works (I already did some testing), I'll be happy to push it to production.
