### ISSUE TITLE
Two delete buttons visible

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#30]
![image](https://user-images.githubusercontent.com/2552726/39383095-e6ea6a12-4a5f-11e8-9d34-6212370f5117.png)

Steps to reproduce:

* Create anonymous paste

**Comment by jkcclemens** [comment]
Are you logged in?

**Comment by lol768** [comment]
Nope

**Comment by jkcclemens** [comment]
Fixed in https://github.com/jkcclemens/paste/commit/66872611bfd63e8143aa3845d3358acc5c049924.

**Comment by lol768** [comment]
:+1:
