### ISSUE TITLE
Actually validate emails

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#32]
Like more than no checks at all.

**Comment by Zarthus** [comment]
i propose `^[^@ ]+@[^. ]+\.[^ ]+$`, html also has input type email which prevents most invalid insertations  on sane browsers.

**Comment by jkcclemens** [comment]
We already use the `email` input type, thankfully!

**Comment by bendem** [comment]
I wouldn't force the `.` in the domain, I have had problems running application on internal networks because of it (yes, `a@localhost` is a valid email).

**Comment by Zarthus** [comment]
just because it's valid doesn't mean we should accept it (spaces in emails are theoretically valid too). I'm assuming the end user has a sane email address; and even then my regex is already lenient.

**Comment by jkcclemens** [comment]
I [ported Firefox's email-checking function](https://paste.gg/18a06db2cd2c451090700a324e9bbefc) from C++.

**Comment by jkcclemens** [comment]
[Here](https://github.com/jkcclemens/paste/blob/master/src/routes/web/auth/register.rs#L54) are the checks done on user data when registering.

**Comment by lol768** [comment]
Did we consider just trying to send a verification link to it? Or was that deemed too annoying from a UX perspective?

**Comment by jkcclemens** [comment]
We probably should. That's a separate issue, though.
