### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#40]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when **my code isn't word wrapped**

**Describe the solution you'd like**
To put it in a clear and concise way, I want word wrapping to happen. It could be toggleable, it could be automatic.

**Describe alternatives you've considered**
I have not considered alternatives.

**Additional context**
https://paste.gg/users/anonymous/b1e02b41a859454ea988930c5439075c

**Comment by jkcclemens** [comment]
I'm upgrading this to "goddamn impossible" with highlightjs somehow. When the switch to Prism is eventually made, I already had it working on that fork.
