### ISSUE TITLE
Favicon contrast

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#41]
**Describe the bug**
Favicon could do with a background for contrast.

**To Reproduce**
1. Go to `paste.gg`
2. Do not click on '....'
3. Do not scroll down to '....'
4. Look at favicon

**Expected behavior**
A clear and concise favicon with contrast.

**Screenshots**

![image](https://user-images.githubusercontent.com/2552726/39665258-e5fea526-5088-11e8-83d3-20920e8ba9a2.png)

**Server and resources version (found in footer)**

![image](https://user-images.githubusercontent.com/2552726/39665279-0eb2a4e0-5089-11e8-8dcf-46dab235fea6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox Developer Edition
 - Version 61.0a1

**Comment by lol768** [comment]
https://github.com/jkcclemens/paste/tree/master/webserver/web/static/favicons

* Where's the source SVG?
* Can we ensure the browser is told about a vector (SVG) icon? This is obviously better than a raster and will look regardless of device DPI

**Comment by jkcclemens** [comment]
>Where's the source SVG? Presumably you didn't manually resize to make these files?

Uhhhh I'd have to find it, but if you download the clipboard icon from FA, it's literally that on a square canvas.

**Comment by bendem** [comment]
https://use.fontawesome.com/releases/v5.0.13/svgs/solid/clipboard.svg

**Comment by jkcclemens** [comment]
Because I can't figure out where the hell you can host an SVG without hosting it yourself, here's a [Gist](https://gist.github.com/jkcclemens/ccfd9d4a03729a08bef45dce83c28bc6) with the quick SVG I made with a background.

**Comment by lol768** [comment]
I dislike the border

**Comment by jkcclemens** [comment]
Added a borderless one to the gist.

**Comment by lol768** [comment]
I like it.

**Comment by jkcclemens** [comment]
[SVG favicons](https://caniuse.com/#feat=link-icon-svg) are only supported in Firefox. I would still advocated for an `ico` to be used as the main favicon.

**Comment by lol768** [comment]
>SVG favicons are only supported in Firefox. I would still advocate for an ico to be used as the main favicon.


Include multiple `link`s of type `icon` with SVG at the end and it should "just work" (TM) - Firefox will prefer the SVG, everyone else will use a raster (and you can probably get away with PNG over ICOs)

**Comment by lol768** [comment]
AKP has a better icon

**Comment by jkcclemens** [comment]
Done in https://github.com/jkcclemens/paste/commit/d890796b96e796e3f64e170cecedabac5e2c3a1b!

Gonna see about switching to dark mode version of the favicon on dark theme, but for now, this is good.
