### ISSUE TITLE
Menu cut off on RHS

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#44]
**Describe the bug**
Menu cut off on RHS

**To Reproduce**
1. Go to https://paste.gg
1. Hover on Login without clicking
1. See issue

**Expected behavior**

Menu not cut off on RHS.

**Screenshots**

![](https://lol768.com/i/LandholderPitiesMeaningTabled)

**Server and resources version (found in footer)**

server: 8a3a894
resources: 8a3a894

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 62.0a2

**Comment by jkcclemens** [comment]
Yeaaaaaah, I've known about this for a while. Don't really know why this is happening, but I'll look into it.

**Comment by lol768** [comment]
`is-right`
