### ISSUE TITLE
Username and display name requirements

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#48]
I dislike usernames now. I guess we should replace the "name" field on users to "display name," too, even though I don't like it.

A valid username is an ASCII string that meets the following requirements:

- Is unique
- Is not in the set of `{"anonymous", ".", ".."}`
- Is at least one byte long
- Is less than or equal to 255 bytes long
- Has no "other" characters (unicode category C)
- Has no leading or trailing spaces
- Contains no whitespace but `0x20`
- Has no instance of two or more adjacent spaces

A valid display name is a Unicode string that meets the following requirements:

- Is at least one grapheme long
- Is less than or equal to 255 graphemes long
- Is less than or equal to 5 KiB
- Has no "other" characters (unicode category C)
- Has no leading or trailing spaces

**Comment by kashike** [comment]
I think it makes sense to restrict the following usernames (mark as "reserved") from being used, too:
- [ ] `account`
- [ ] `login`
- [ ] `register`
- [ ] `static`

When `/<username>` is a route:
- `account` will redirect to account settings for authenticated users, or to `/login` for unauthenticated users
- `login` will redirect to wherever you were previously for authenticated users.. apparently, or the login form for unauthenticated users
- `register` will redirect to `/` for authenticated users, or the registration form for unauthenticated users
- `static` will 404 due to there not being an asset at the path.
... etc

**Comment by lol768** [comment]
NFC:

>Hangul is one where NFC won't work well. Yes, we actually already encode all possible modern hangul syllable blocks in NFC form as well, but this ignores characters with double choseongs or double jungseongs that can be found in older text. Which you sometimes see in modern text, actually.

> All Indic scripts (well, all scripts derived from Brahmi, so this includes many scripts from Southeast Asia as well like Thai) would have trouble doing the NFC thing.

**Comment by lol768** [comment]
Also, consider adding a byte limit too. You can do silly things with unicode like take 7 codepoints to produce a single grapheme cluster

**Comment by jkcclemens** [comment]
Does NFKC have the same problem?

**Comment by jkcclemens** [comment]
>Has no nonspacing marks (unicode category Mn)

Not allowing [Mn](https://www.fileformat.info/info/unicode/category/Mn/list.htm) effectively disallows all diacritical marks. However, a sequence such as `\u0301a` or "combining acute accent" and "a" (which does not combine – the "a" would need to be before the combining mark) would still pass, despite the mark being invisible. Thoughts on this would be appreciated.

![example](https://i.imgur.com/FsM1lt5.png)

**Comment by jkcclemens** [comment]
I've changed the issue to represent both usernames and display names. The primary factor that made me choose ASCII (still stored as Unicode strings, but only characters defined by the ASCII charset will be allowed) for usernames is that I want them to be easily typeable by anyone.

With that being said, the problem of nonspacing marks is now a nonissue, since display names need not be unique. My question now is what formatting marks can be potentially detrimental?

**Comment by lol768** [comment]
M̸̡̫͍̥̯̭̥ͬ͛̈́̇ͤ̐́͘y̸̨̛̘͍̻̠̥̤͚͉̼̲͈̖̲̟̹̯̲̟͉̎͆̂ͨ̈́ͬͤ͐ͮ̚ ̸̢̫̗̲̰̮̬̺̼͖̙͎̱̣̱͖͈ͬ͋̋̅ͫ͐͛̎̈q̸̧̫͈͎̮̖̰̥͆́̍̎͆̐̎͂̐͐̔͌͗̀͞u̵̸̡̡͈̥̦̩̹̱̺̮͈̓ͧ͌̅ͤͪͧ̽͊͌̔͋̐͢ͅe̵̶̪͚͔ͭ͗̒͋ͮ̐͛ͧ̆͌̐̒ͩ̍̐͆̓̽ͅs̷͕̖͎̝̬̬͉̹͉̱̰̄̍̈́̋͢͢͝t́̾̂̅͗ͤ̏̈ͣͩ̈́ͣ̃̄ͤͮ͊̂̚҉̴̜̠̬̫̰̤͚̲̟͎̩̦͖͈̘̗̕͞į̧̫̲̫͎͓̳̲̝͉̣̤̥ͧ͂ͩͬ͗ͧͤ͑͌ͩͫ͗ͨͦͣ̑́̚ͅͅở̂͗ͪ͂͋ͧ̏̃͊̋́͡҉̴҉̞͙̹͇̗̻̞̱̩̫̭̙̲nͩ̄ͣ̑̐̍ͨ̈͒̈͏͞͏̥͈͎̻͇͎̰̜̰͙͢ ̡̹̰͇̤̦̗̯͚̘̜͙̭̦̬͇̞͇ͦ̆̈́̾̆̄́͞n̸̷̡͙͉̖̯̮ͫ̌̎̽ͯͬ̀̚o̢͈͙̥͍̝̩̟͕̗̠͕̬̼̪͂͊̏͑̒͌ͦ̌ͬ͒ͬw̷̢̲̲̹͍̲̳͇̿̌̓̅̄ͣͤͬ̒ͩͤ̈́̌ͪ͘͟ͅ ̧̡͙̦̹̞̼̖̲̠̝̦̭̥̋͂ͧ͂̃ͥͦ̍͐́̚͢͜i̧̧̞̩̪̺͙ͪ̾ͧ̐͊͗́s̬̠̺̬̱̗̳̱̝̳̯̉͗͛ͤ̃̿͋̋ͭ͜͢ͅ ̸̴̷̠͇͎̠͖̟̯̠ͮ̎̇̐̇ͭẃ̉͂̓̌ͯ̑͛̑ͪ̎̎̽ͤͧ̄͞҉̠͚͈̻̤̯̩̫̮̠͘h͒̾̿̒ͧͩͯ͗́͛̀͗̇́̄̔̋ͫ̊҉̶̟̖̝̞̝̩̪̖͟͝͝a̴̘͉̙̱̩̤̩̞͇͖̯͔͈̱̰͐̀̆̓̉͂͊̅̊͢tͦͮ̌̏̎͌̓̅̍ͣ̿͠͏̴͎͚͖̟̮̹̤̥̙͚̹̰̙̯̮͖̰̲͘͡ͅ ̖͇̺̙̜̝͓͖̥͓̙̯͐̉̉̑̉͂ͥ̇̊͑̾ͮ̂ͮ̏̇̽͒̆́̕͟͡f̡̧̤̼̬̯̮̬ͤ̊͒̄̍̽́̽͋̈́̃̈ͯ̇ơ̴̢̠͔̖̐ͥ̊͛̏̓͂̏̉̽̾̌͗̚͘r̲̯͓͎̖̥͙̭̥̖̺̲̻͊͑̑ͣ̀ͮ͌̎̈́ͧ̆͐ͪ̈͑̀͢m̶̨͖̠͔͍̲̥̘̣̘̻͍̜̯̍̊ͦ̊̎̂̽ͧ͌ͩ̀̕̕͟a̶̶̔̍͑҉̬͈͇͍t̶͒ͥ̈͊ͥͤͦ̏̿͆͌̽̇͆̓̈͢͜҉̘̖̳t̸̵̻̦̣̥͓͍͎̳̥͖̜̝͎̝͍͔̔ͮ̇̂ͣ̓̅͑̇ͤ͂̂̔̌̒ͭͩ͑i̸̶̶̵̭͙̰̝̮̤͖͇̼͎̟͓̳͉̳͕͔̤ͦ̆͑ͭ͛̍̄̿ͮͫͪ̚n͗̈́̉͢͏͓̺̝̻̠̗͉̭̀g͈̟̳̬̯͚͕͎͛ͨ͆ͣͩ̍ͧͬ́͝ ̝͖͈̞ͧ͊͆͒̆͂͌ͬͥ̔̕̕m̫͚̜̩͙͇̖̬̹͐̆̿ͤ̒̏̈́̐̽̏͜͝ͅa̪̹̮̗̤͓̩͈͊̍ͧ̑̄ͫͦ̕̕͘ṙ̢̛͇̯̞͉̜̖̝̘̺͉̥̯̬͇̤̣ͧ̉ͩͤͩ͊̋͂ͣ̾̚͡͡ḳ̷̡̤͉͇͕̭͓̦̩̩̬͉͇̼͗͋͗̽̋ͨ͋̈́ͧ̕͡ͅs̢̱͔̟̱̖͕͓̯̞̱̄̂̎ͩͭͣ͆̌̏͒̃̍̈͋͐ͯ͘ ͫͭͮ́̓ͤͨ͂ͤ̿́͏̧̡̨͔͚̙̬̻̫̩̦̦͇͕͕̗̲͖c̴̬̞̻͙̥͊̽ͪ̏́̒ͩͯͤͤ͛͐̀̄͒́̕͡͡a̢̜̲̰͈̯̠̯͔͍̬̪̰̝̟̱̠̹͗̂͒̊ͦͫͯ̌̓́̂̐ͦ̍ͥ̋̾ͅͅn̵̸̖̹̩͙̺̘̭̘̭̺͍͚̾̔ͦ͒͂̊͗͌̐̅̓̿ͥͩͫͦ͊̊ͅͅ ̵̵̨̼̞̬̜͑̇̿̈͛̿̀͝b̋ͭ̀͐͛̃͋̅̇͑͌͏͏̩̻̙͕̱̪͎̙e̶͓͕͖̩̠̲̘̜̤͉ͮ͌̎̿̃̔́͠ ̧̡̩͙̗͙̥̹̙̰͖͖̣͔͙͚̭͓̻̲̈ͫ̾͊ͤ̓ͬ͛̒̎̄̇̉͒ͤͫ͌̑͞͞p̟̼͙͇͓͓͙̣͓̟̙̬̹͎̄̍͛̓͒̄̏͐̆́͢o͚̻̦̗̻̙̗̤͈͐͑ͤ̉ͦ̌̄ͮ̀̄̑͗̈́̾̄̏̄ͨ́͡ͅt̸̘̥͕̫̬̥̘̣̪̽̇̋͂͞ȅ̶̾̇͂̈̐̅̅҉͍̱̭̺̤͍̫̯̝̥͙͡n̡ͮ̏͛͑̔̿̋̾ͩ̊ͭ̏͂ͫ̋͑͢͏̨͏̰̺͍̼͓̬̥̠̼̤̜͉͈ͅt̸͙͕̙̲̻͈̲͉͉̪͉̮͙̲̠̖̰̙̝ͥ͋̃ͫ͑ͩͪ͗̊ͣͯ͑ͣͪ̅͊́̚͢i̵̷̡̛̮̭̟̼̹̜̜̅̒̓̆͌͐͟ã̸̳͙̮͈͉̣̮̲̝͓̹̺̘̜͊̽ͨ̒̒̇̌̍͐̂ͥ̊͘͘͢l̴̳̻͚̺̹͓ͯ͊͗͊̀̚͘͢͜ͅļ̧ͬ̃͋̓̆ͭͮ̈́͛̈́ͪ̄ͭ͌̕͏̠̱̜̲̜̘̳̘͓̦̜͔͓̗̳̥͈ͅŷ̷̶͔͚̮̬̩̭̫̗̮͂̏̒̆͜ ̵̡̘̣̹̹̌̾͂ͩ̾̀ͩͣ̐̐ͪ̽̃ͨ̃̕d̠̣̖̻̮̠̤̝͉̪̳͉̣̦͐͛ͣ͊̇ͭ̇ͣ͗̐͂͘͜͠ĕ̸̡̢̛̩̦̙̜ͧ̓̇ͭ̍ͯ̿ͥͬ́̑̾ͨ̚t̷̨͚̘͚̘̲̞̹̪̪̠̩͕̭̮͖̣̙̓̄ͪ͗ͫ͒́r̢̡̩͍̰̞͑ͬ̍͊ͬ́ͅĩ̴̧̠̟̣̜̬̺̘͍̊̏ͤ͂ͤ͒͌̚͢͟m̷̧̟̣̰̤̰̳̻̰͍ͯͧ̉̈͂̂ͯ̆̈ͤͬͦ͑ͧ́̕͢e̵̛̛̗͈̞̟̻̖̗̟͚͎̗̱͈̙ͮ̎̔͋̀ͥ͒ṅ͇͕͖̩̒ͣ́́͢͢͞t̡ͧͦ̊͒ͤ̽͋̐̓̈́͟͠͏̮̱̺̤͇͉͖͙̘͖̝̺͖͇͔͚̜ã̸̙̮̰̩̙̠ͥ́̓ͪ̀͑ͯ̐́̀͢͜l̶̑̃ͩ͂͝͏҉͓̬͙͎̼͇̻̭͎̟̳̩͚͔̩̟̝ͅ?̨̨̼̭̞̖̗͓͎̙̮͉̓̄͊̓̎͐̀̚͝

**Comment by jkcclemens** [comment]
Closing because requirements were implemented (primarily in https://github.com/jkcclemens/paste/commit/851f41dfd1e18bb668cf15c72e33b30d37d9e4cd) and no other comments have been made.
