### ISSUE TITLE
Clicking edit doesn't do anything anymore

### ISSUE THREAD

**Issue by whitfin** [jkcclemens/paste#49]
**Describe the bug**
When I click edit, nothing happens. It did a few days ago (maybe like a week) but appears to no longer invoke anything. 

**To Reproduce**

1. Make a new paste
2. Try to edit it :)

**Expected behavior**
Edit screens should come up, with the ability to modiy.

**Server and resources version (found in footer)**
 - Server: https://github.com/jkcclemens/paste/commit/7e8b63312ef57d8dd9636ba25221e180313a351b
 - Resources: https://github.com/jkcclemens/paste/commit/5037e3a0a5a547bf352f42052f69793369335428

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 58?

**Comment by jkcclemens** [comment]
I can't reproduce this. Are there any errors in the console?

**Comment by whitfin** [comment]
@jkcclemens I'm using the hosted version over at paste.gg, perhaps it's just out of date?

Nothing in the console. I'm trying to edit an unlisted paste I made whilst signed in :)

**Comment by jkcclemens** [comment]
Yeah, I'm testing on paste.gg, too. You're clicking the blue pencil and nothing is happening? What's the HTML of the link when you inspect it?

```html
            <button class="button is-info is-large">
              <a href="/pastes/jkcclemens/f54ab606faee4257986aa70f61f202d3/edit">
                <span class="icon is-large">
                  <svg class="svg-inline--fa fa-pencil-alt fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="pencil-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M497.9 142.1l-46.1 46.1c-4.7 4.7-12.3 4.7-17 0l-111-111c-4.7-4.7-4.7-12.3 0-17l46.1-46.1c18.7-18.7 49.1-18.7 67.9 0l60.1 60.1c18.8 18.7 18.8 49.1 0 67.9zM284.2 99.8L21.6 362.4.4 483.9c-2.9 16.4 11.4 30.6 27.8 27.8l121.5-21.3 262.6-262.6c4.7-4.7 4.7-12.3 0-17l-111-111c-4.8-4.7-12.4-4.7-17.1 0zM124.1 339.9c-5.5-5.5-5.5-14.3 0-19.8l154-154c5.5-5.5 14.3-5.5 19.8 0s5.5 14.3 0 19.8l-154 154c-5.5 5.5-14.3 5.5-19.8 0zM88 424h48v36.3l-64.5 11.3-31.1-31.1L51.7 376H88v48z"></path></svg><!-- <i class="fas fa-pencil-alt"></i> -->
                </span>
              </a>
            </button>
```

**Comment by jkcclemens** [comment]
Oh, interesting. I *can* reproduce this on Firefox, but not on Chrome. I'll investigate.

**Comment by jkcclemens** [comment]
Fixed on paste.gg now!
