### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#50]
Need some way to reset passwords securely. @lol768 surely has input.

**Comment by lol768** [comment]
Here's my view of an ideal password reset mechanism:

* User submits email requesting password reset
* If user has not been rate limited for this activity already, a token 3-tuple is generated and persisted:
  * The first item in the typle is a "selector" - a UUID used to retrieve the token. This is probably a primary key
  * The second item is a reasonable number of random bytes generated with a secure RNG and passed through a BCrypt-like function. The idea here is to ensure that even if the database is compromised, it is not possible to recover the original plaintext token secret.
  * The third item that makes up the reset token is an expiry timestamp. I think 30 minutes is reasonable.
* The secret part of the token should only be used to send an email to the user and them removed from memory. The URL should be of the form `https://paste.gg/path/to/reset/?selector=11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000&secret=cde84bff512f60ee65b805840b1847422f4f33ec120981c4adb343fdc103cd30`. The encoding used (hex here) is up to you. URL-safe Base64 is fine too.
* Once the user has changed their password, they should be automatically logged in for a frictionless UX. The database entry should be removed.

**Comment by jkcclemens** [comment]
If the user goes to the reset route with a valid selector but invalid secret, does it invalidate the reset or show an error?

**Comment by jkcclemens** [comment]
>The server should retrieve the record using the selector and verify the secret is correct using the hash verify function.

(Asked on IRC) After verifying the secret, what sort of token should be used in the form presented to the user to reset their password? Is using the selector enough? Could the entry in the database have a `session_id` column that is restricted to a single session when the secret is validated, so that only that session is allowed to change the password?

Anyone could POST to the reset password route, which makes me wonder if the selector ID is secure enough.

**Comment by jkcclemens** [comment]
The [`password_reset`](https://github.com/jkcclemens/paste/tree/password_reset) branch is now updated. The only thing it's missing is rate limiting. I don't want to deploy to paste.gg until I'm sure it's not loaded with vulnerabilities, though.

**Comment by jkcclemens** [comment]
The outline that @lol768 provided above should be fully implemented in https://github.com/jkcclemens/paste/commit/ffdf91786d6710c11c908bea36c2193a92f05827. Testing will need to be done before it's pushed to paste.gg.

**Comment by jkcclemens** [comment]
>🎉 Can we get a staging site?

Yeah, this will take some set-up, but I'm going to add one that you can go bananas on.

**Comment by jkcclemens** [comment]
@lol768 Have you tested this on staging?

**Comment by lol768** [comment]
Awesome! ![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/24px-Microsoft_logo.svg.png)
