### ISSUE TITLE
Store the deletion key in localstorage for anonymous pastes

### ISSUE THREAD

**Issue by Zarthus** [jkcclemens/paste#61]
Store the deletion key for anonymous pastes in localstorage so that the deletion modal can be prefilled for the same user.

**Describe alternatives you've considered**
#60

**Comment by bendem** [comment]
I'd argue that there shouldn't be any need to show the field if the key is in local storage.

**Comment by Zarthus** [comment]
yeah, you could turn it into a different modal if the key is known ('do  you want to delete it yes/no') but there'd be little difference to just showing the modal prefilled in the first place.

**Comment by jkcclemens** [comment]
My real concern is the safety of storing deletion keys in local storage and how long they'll be there. There must be an expiry time.

**Comment by bendem** [comment]
could store it in sessionStorage then?

**Comment by Zarthus** [comment]
```
The sessionStorage property allows you to access a session Storage object for the current origin. sessionStorage is similar to Window.localStorage; the only difference is while data stored in localStorage has no expiration set, data stored in sessionStorage gets cleared when the page session ends. 
```
It'd make more sense for it to be preserved longer (e.g. a week, month, whatever.)
