### ISSUE TITLE
Set language for a file instead of relying on extension

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#62]
Allow specifying a language for a file in both the API and web interface.

Presumably the language should be one out of a fixed set to be of any use. An unrestricted string doesn't do much good when trying to determine code highlighting on a file in the web interface.

Should the language set be the set of what is supported for syntax highlighting? If so, should the field in the API make that clear (`language` vs `highlight_language`, etc.)?

Is this useful data to return in API queries?

**Comment by kashike** [comment]
`highlight_language` seems reasonable.

**Comment by jkcclemens** [comment]
Pushed to staging. Should be full GET/PATCH/POST support for both the API and web UI. I've tested the web UI, but the API is untested.

Currently, the web UI uses the correct values in the `select` tag, so there's no need to have the user know the values for each language, but the API requires manual selection, so any API user would need to know the name that paste will correctly deserialise. For now, those values are the [lowercase names of the Language enum members](https://github.com/jkcclemens/paste/blob/2a6e3c311197e99cc424da6444120984ff1ff61a/webserver/src/utils/language.rs#L15). Should they instead be the hljs classes or the prettified names?

**Comment by jkcclemens** [comment]
Something to note is that naming a file `*.md` and setting the highlight language will still attempt to render the file as Markdown.

Should rendering only be attempted if the file is `*.md` with no highlight language OR if the file has a highlight language set to Markdown regardless of file name?

**Comment by lol768** [comment]
There should be markdown (render) and markdown (code) languages. `.md` should by default map to the former.

**Comment by lol768** [comment]
What reason is there for explicitly non-rendered Markdown as a separate language option?

You can syntax highlight it without rendering it. Useful for displaying the syntax (e.g. of references, tables, images etc) for people to learn from

**Comment by jkcclemens** [comment]
There's already a method to display both the source and the rendered output.
