### ISSUE TITLE
Auto linking links in rendered markdown

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#65]
Issue template:

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my markdown links aren't autolinked.

**Describe the solution you'd like**
I'd like my markdown links to be autolinked.

**Describe alternatives you've considered**
I've considered keeping markdown links not linked.

-----

Actual issue:

We should autolink links in rendered markdown documents. This should only apply to sensible links:

* `https://` protocol
* `http://` protocol
* `mailto:` protocol

These links must not be allowed to include credentials (`https://username:password@example.com`).

We could potentially allow other types of link too, but these could lead to abuse:

* `magnet://`
* `stream-magnet://`

These are _not_ sensible links:

* `javascript://`
* `ftp://`
* `gopher://`

All links should be:

* `rel=noopener`(we should be `disown-opener` CSP'd though too)
  * potentially `noreferrer` too
* `referrerpolicy`'d
* Appropriately escaped
* Annotated with an external symbol/icon - https://fontawesome.com/icons/external-link-alt?style=solid
* `target=_blank`

**Comment by jkcclemens** [comment]
I agree with this, but the current CommonMark parser being used does not support this, and I may change.

Currently, we use [pulldown-cmark](https://github.com/google/pulldown-cmark) (the same parser used for Rust's doc comments), but it does not appear to be actively maintained. There is little to no interaction via issues and evidently no active development.

I am interested in switching to [comrak](https://github.com/kivikakk/comrak), which appears to be actively maintained, specifies that it supports GFM, and has more features, including autolinking.

**Comment by jkcclemens** [comment]
Whoops, forgot to close via commit message.

Done in https://github.com/jkcclemens/paste/commit/80279084d90cd493bb26d239fb966fdde159eea7.
