### ISSUE TITLE
Feature req: autolink 🐻 domains

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#66]
https://paste.gg/pastes/anonymous/7589e3db0b654f05977d84fb77ab7efa#

Should be autolinked to `https://webchat.esper.net`

https://publicsuffix.org/list/

### FAQ:

**Do we want to assume HTTPS as the default?**

[Yes](https://github.com/thelounge/thelounge/pull/2397#discussion_r185695728).

**Comment by jkcclemens** [comment]
This is out of scope for paste. Please file an issue at [comrak](https://github.com/kivikakk/comrak). For what it's worth, comrak is supposed to implement the [GFM spec](https://github.github.com/gfm/#autolinks-extension-).

**Comment by lol768** [comment]
I'm afraid this would need a GFM spec change, the autolink extension does operate correctly but requires `www.` at the start of the URL.

**Comment by lol768** [comment]
https://github.com/github/cmark/issues/98
