### ISSUE TITLE
Shortened routes

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#69]
Proposal for web interface: `/users/` -> `/u/`, `/pastes/` -> `/p/`

I don't believe this should be necessary for API routes.

**Comment by lol768** [comment]
Reminds me of Reddit :+1:

**Comment by jkcclemens** [comment]
Whoops, meant to mention this issue in https://github.com/jkcclemens/paste/commit/1fe6f5e668616f07be34084173130c3887b123f3.

Sneakily snuck this change in. Will update staging soon.

**Comment by jkcclemens** [comment]
Nothing seems to have crashed and burned now that this is on production.
