### ISSUE TITLE
Ability to create custom url for note

### ISSUE THREAD

**Issue by egoarka** [jkcclemens/paste#71]
Would be cool if you had the ability to refer a note to unique url
e.g. https://paste.gg/supernote

It'd become super easy to memoize and share with friends

**Comment by kashike** [comment]
I don't think this is a good idea - it would make guessing paste links a lot easier.

**Comment by meltinglava** [comment]
I think this should be an toggle option for the hoster.

**Comment by AKPWebDesign** [comment]
Perhaps it could be done in a similar manner to what git.io does for GitHub.
