### ISSUE TITLE
Background around corners is wrong colour in Firefox for Android

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#74]
![Screenshot](https://i.imgur.com/IDexNin.jpeg)

**Comment by lol768** [comment]
This is above the "Add file" button. Applies to all four corners.

**Comment by jkcclemens** [comment]
We had this discussion before in IRC, too. I cannot reproduce on my phone or on desktop.

![screenshot](https://i.imgur.com/usmrhuY.png)

If only there were some format where I could know the conditions under which you could reproduce this issue.

**Comment by lol768** [comment]
If only!

**Comment by jkcclemens** [comment]
Leave it to Firefox mobile to be a pain in the ass.

**Comment by lol768** [comment]
If past experience is anything to go by it's following the spec and chrome isn't :p

**Comment by jkcclemens** [comment]
Okay, I *can* reproduce on Firefox's mobile app on Android, so I guess now to learn how to open the dev tools and see why the CSS isn't working.

**Comment by lol768** [comment]
:tada: 
:tada: 
:tada:

**Comment by kashike** [comment]
:heavy_check_mark: :heavy_check_mark: :heavy_check_mark: 
:heavy_check_mark: :tada: :heavy_check_mark: 
:heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
