### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#79]
- [x] Enable (on staging!)
- [x] Disable (on staging!)
- [x] Backup codes

**Comment by lol768** [comment]
Totp presumably?

**Comment by jkcclemens** [comment]
Indeed.

**Comment by jkcclemens** [comment]
Done in https://github.com/jkcclemens/paste/commit/4ebd263e4afa89ac6eededecde1d805abaa1e649!
