### ISSUE TITLE
TLS issues with Firefox

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#83]
[net_trace.asc.txt](https://github.com/jkcclemens/paste/files/2343397/net_trace.asc.txt)

**Describe the bug**
TLS connections seem to fail to establish, see attached Wireshark trace.

**To Reproduce**
1. Browse to `https://paste.gg`

**Expected behavior**
Connection to succeed, page to display.

**Screenshots**

![](https://lol768.com/i/ReservedGrandmaPerpendicularConstitute)

![](https://lol768.com/i/WaterspoutUniversesAbyssPopulate)

**Server and resources version (found in footer)**

**Cannot determine**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Browser Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0 `63.0a1 (2018-09-01)`

**Additional context**
N/A

**Comment by jkcclemens** [comment]
Solved. Culprit was bad TLS 1.3.
