### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by lucko** [jkcclemens/paste#85]
**Describe the bug**

I'm unable to register for a new account. This error is shown:

![](https://luck.sh/xWUBtNSDVwfrm7O0Zxp8EPmFNlk=)

And the following is printed to the JS console.

```
anchor:174 GET https://www.gstatic.com/recaptcha/api2//styles__ltr.css 404 ()
anchor:175 GET https://www.gstatic.com/recaptcha/api2//recaptcha__en.js 404 ()
anchor:179 Uncaught ReferenceError: recaptcha is not defined
    at anchor:179
(anonymous) @ anchor:179
anchor:174 GET https://www.gstatic.com/recaptcha/api2//styles__ltr.css 404 ()
anchor:175 GET https://www.gstatic.com/recaptcha/api2//recaptcha__en.js 404 ()
anchor:179 Uncaught ReferenceError: recaptcha is not defined
    at anchor:179
```

**To Reproduce**
1. Simply navigate to `https://paste.gg/register`

**Server and resources version (found in footer)**
server: 0078a1e
resources: 0078a1e

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  68.0.3440.106 

**Additional context**
Note that I've also tested with Firefox 60.0.1 and get the following errors:

```
Loading failed for the <script> with source “https://www.gstatic.com/recaptcha/api2//recaptcha__en.js”.    anchor:175
ReferenceError: recaptcha is not defined[Learn More]   anchor:179:7
```

**Comment by jkcclemens** [comment]
Hi!

Yes, this is due to reCAPTCHA not supporting CSP and not being backwards-compatible. 

As discussed on IRC, we will be removing reCAPTCHA, which should happen today. I'll close this issue once reCAPTCHA is removed and that code is pushed to production.

**Comment by jkcclemens** [comment]
Fixed in prod now! Thank you for letting us know!
