### ISSUE TITLE
Back-button functionality

### ISSUE THREAD

**Issue by apnewberry** [jkcclemens/paste#89]
**Is your feature request related to a problem? Please describe.**

I type some text into the box, click "Submit anonymously", notice some change I want to make, press the browser's Back button. My text is gone, and if I re-paste it and fix the change, clicking "Submit anonymously" again gives "Invalid anti-CSRF token."

**Describe the solution you'd like**
Clicking Back would fill the page with my last attempt, and submitting it again would be successful.

**Describe alternatives you've considered**
An "Edit" button on the view page. This would be nice anyway, but wouldn't exactly solve the problem since my instinct is to go back and retry rather than looking for another button.

**Comment by jkcclemens** [comment]
Whoops, I meant to reply to this much earlier, but I archived it in my email on accident!

I agree that you should be able to go back and repaste, but I'm not sure about the how.

I do *not* agree that you should be able to edit anonymous pastes, and that will likely never be implemented.

@lol768, I'm curious about your input. Going back would load the same anti-CSRF token in the browser, but valid tokens are deleted after one use. Keeping them around after use feels unsafe (though correct me if I'm wrong).

I'm open for ideas on how to make clicking back and resubmitting work correctly, and I'll think about it more.

**Comment by lol768** [comment]
>but valid tokens are deleted after one use

So, out of interest: What's your thinking behind what this is protecting against? What attack does this approach stop that using one token per session doesn't stop?

There are some other 'fixes' (such as setting `no-store, no-cache, must-revalidate` etc for your cache control headers) but I suspect they'll make the browser lose the old input. It's a tricky one.
