### ISSUE TITLE
Add description field for pastes

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#9]

**Comment by lol768** [comment]
Markdown?

**Comment by jkcclemens** [comment]
I was thinking descriptions would just be a tagline, like GH repos. You can always add a `description.md` to a paste.

**Comment by lol768** [comment]
>I was thinking descriptions would just be a tagline, like GH repos

Fair.

>You can always add a description.md to a paste.

Would be cool if frontend special cased this and displayed it prominently

**Comment by lol768** [comment]
![image](https://user-images.githubusercontent.com/2552726/38826482-d787ecc2-41a7-11e8-9977-216a6e668518.png)

THE IRONY

**Comment by jkcclemens** [comment]
>Would be cool if frontend special cased this and displayed it prominently

Similar to README files on repos? That could be arranged.
