### ISSUE TITLE
Store deletion keys in database hashed

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/paste#94]
Deletion keys should be hashed with a relatively simple hash (SHA-512 is fine) then stored in the database.

The prevailing issue with this is how to make a migration. This is obviously a breaking migration. Postgres 11 has a `sha512` function, but I think requiring 11 is a little much. 10 has `pgcrypto`, but that requires superuser permission to add, which I can't assume in migrations.

**Comment by lol768** [comment]
Have you thought about supporting both kinds in the app?

**Comment by jkcclemens** [comment]
No, but that doesn't sound fun at all.

**Comment by jkcclemens** [comment]
- Deletion keys are currently stored as the PostgreSQL `uuid` type. The migration would need to change that to store them as a `varchar(128)` or `text`.
- The model in the backend would need to be updated to use a `String` instead of a `Uuid` (store UUIDs in simple format).
- All logic involving deletion keys would need to check the key string length - 32 bytes is a UUID, 128 is a hash - and compare accordingly.

Most probably, the best idea is using [pwhash][pwhash] in interactive mode (same way we check user passwords). This handles hashing and salting with constant-time comparison, too.

Honestly, I don't think this would be a hard issue for a first-timer with a little guidance, so I'm marking this as a good first issue for an intermediate Rust programmer.

[pwhash]: https://docs.rs/sodiumoxide/0.2.4/sodiumoxide/crypto/pwhash/index.html
